baseURL = 'https://eff4ctt.github.io/'
languageCode = 'fr-fr'
title = 'effect - Cybersecurity Blog'

[params]
  author = 'Votre Nom'
  description = 'Cybersecurity Researcher & CTF Player'
  tagline = 'Writeups, Research & Security Analysis'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Articles'
    url = '*../content/posts/'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = '../content/about/'
    weight = 3

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    lineNumbersInTable = true

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

